name: health_care_pt2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.4.0
  get_storage: 2.0.3
  lottie: 2.1.0
  google_sign_in: 5.4.2
  firebase_auth: 4.2.1
  cloud_firestore: 4.2.0
  firebase_storage: 11.0.8
  image_picker: 0.8.6
  avatar_glow: 2.0.2
  emoji_picker_flutter: 1.0.6
  introduction_screen: ^3.1.1
  google_nav_bar: 5.0.6
  simple_animations: ^1.3.3
  google_fonts: 3.0.1
  accordion: 2.5.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/logo/.
    - assets/lottie/.
  uses-material-design: true

