// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDykxQW2KhpJQJhMrqiEfROfBgAbcoHrXo',
    appId: '1:441069731166:web:a133cb040b3e035bed63cf',
    messagingSenderId: '441069731166',
    projectId: 'health-care-pt2',
    authDomain: 'health-care-pt2.firebaseapp.com',
    storageBucket: 'health-care-pt2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoEsSooBDLjZZ1MqESovYNq0Xgy0sktvc',
    appId: '1:441069731166:android:96fca61e961347f4ed63cf',
    messagingSenderId: '441069731166',
    projectId: 'health-care-pt2',
    storageBucket: 'health-care-pt2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ1QpWup3TP8yP5DSr7-dL4lWg5nfNl1c',
    appId: '1:441069731166:ios:ab4f3ca7a7cc7a5eed63cf',
    messagingSenderId: '441069731166',
    projectId: 'health-care-pt2',
    storageBucket: 'health-care-pt2.appspot.com',
    androidClientId: '441069731166-c3bhtust4vgvlknuuacum6nutdnt2qu7.apps.googleusercontent.com',
    iosClientId: '441069731166-6l725e01i2mt2lonookm0pkpa0rgf0b8.apps.googleusercontent.com',
    iosBundleId: 'com.healthcarept2.healthCarePt2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ1QpWup3TP8yP5DSr7-dL4lWg5nfNl1c',
    appId: '1:441069731166:ios:ab4f3ca7a7cc7a5eed63cf',
    messagingSenderId: '441069731166',
    projectId: 'health-care-pt2',
    storageBucket: 'health-care-pt2.appspot.com',
    androidClientId: '441069731166-c3bhtust4vgvlknuuacum6nutdnt2qu7.apps.googleusercontent.com',
    iosClientId: '441069731166-6l725e01i2mt2lonookm0pkpa0rgf0b8.apps.googleusercontent.com',
    iosBundleId: 'com.healthcarept2.healthCarePt2',
  );
}
